spring:
  application:
    name: api-backend
  cloud:
    nacos:
      config:
        namespace: 75574c3c-ce75-4af6-bcfb-3e027c326985
        server-addr: nacos.dev.love-ext-dns.com:8848
        group: DEFAULT_GROUP
        username: nacos
        password: lovempnacos
        file-extension: yml
        shared-configs:
          - dataId: common.yml
            group: DEFAULT_GROUP
            refresh: true
          - dataId: redis.yml
            group: DEFAULT_GROUP
            refresh: true

  config:
    import:
      - nacos:api-backend.yml
      - nacos:common.yml
      - nacos:redis.yml

springdoc:
  default-flat-param-object: true


