alter table love.mer_user_admin_business_info alter column state type varchar(32) using state::varchar(32);

update love.mer_user_admin_business_info set state='Alabama' where state='1';
update love.mer_user_admin_business_info set state='Alaska' where state='2';
update love.mer_user_admin_business_info set state='Arizona' where state='3';
update love.mer_user_admin_business_info set state='Arkansas' where state='4';
update love.mer_user_admin_business_info set state='California' where state='5';
update love.mer_user_admin_business_info set state='Colorado' where state='6';
update love.mer_user_admin_business_info set state='Connecticut' where state='7';
update love.mer_user_admin_business_info set state='Delaware' where state='8';
update love.mer_user_admin_business_info set state='Florida' where state='9';
update love.mer_user_admin_business_info set state='Georgia' where state='10';
update love.mer_user_admin_business_info set state='Hawaii' where state='11';
update love.mer_user_admin_business_info set state='Idaho' where state='12';
update love.mer_user_admin_business_info set state='Illinois' where state='13';
update love.mer_user_admin_business_info set state='Indiana' where state='14';
update love.mer_user_admin_business_info set state='Iowa' where state='15';
update love.mer_user_admin_business_info set state='Kansas' where state='16';
update love.mer_user_admin_business_info set state='Kentucky' where state='17';
update love.mer_user_admin_business_info set state='Louisiana' where state='18';
update love.mer_user_admin_business_info set state='Maine' where state='19';
update love.mer_user_admin_business_info set state='Maryland' where state='20';
update love.mer_user_admin_business_info set state='Massachusetts' where state='21';
update love.mer_user_admin_business_info set state='Michigan' where state='22';
update love.mer_user_admin_business_info set state='Minnesota' where state='23';
update love.mer_user_admin_business_info set state='Mississippi' where state='24';
update love.mer_user_admin_business_info set state='Missouri' where state='25';
update love.mer_user_admin_business_info set state='Montana' where state='26';
update love.mer_user_admin_business_info set state='Nebraska' where state='27';
update love.mer_user_admin_business_info set state='Nevada' where state='28';
update love.mer_user_admin_business_info set state='New Hampshire' where state='29';
update love.mer_user_admin_business_info set state='New Jersey' where state='30';
update love.mer_user_admin_business_info set state='New Mexico' where state='31';
update love.mer_user_admin_business_info set state='New York' where state='32';
update love.mer_user_admin_business_info set state='North Carolina' where state='33';
update love.mer_user_admin_business_info set state='North Dakota' where state='34';
update love.mer_user_admin_business_info set state='Ohio' where state='35';
update love.mer_user_admin_business_info set state='Oklahoma' where state='36';
update love.mer_user_admin_business_info set state='Oregon' where state='37';
update love.mer_user_admin_business_info set state='Pennsylvania' where state='38';
update love.mer_user_admin_business_info set state='Rhode Island' where state='39';
update love.mer_user_admin_business_info set state='South Carolina' where state='40';
update love.mer_user_admin_business_info set state='South Dakota' where state='41';
update love.mer_user_admin_business_info set state='Tennessee' where state='42';
update love.mer_user_admin_business_info set state='Texas' where state='43';
update love.mer_user_admin_business_info set state='Utah' where state='44';
update love.mer_user_admin_business_info set state='Vermont' where state='45';
update love.mer_user_admin_business_info set state='Virginia' where state='46';
update love.mer_user_admin_business_info set state='Washington' where state='47';
update love.mer_user_admin_business_info set state='West Virginia' where state='48';
update love.mer_user_admin_business_info set state='Wisconsin' where state='49';
update love.mer_user_admin_business_info set state='Wyoming' where state='50';
update love.mer_user_admin_business_info set state='Puerto Rico' where state='51';
update love.mer_user_admin_business_info set state='unknown' where state='100';


alter table love.u_address alter column state type varchar(32) using state::varchar(32);

update love.u_address set state='Alabama' where state='1';
update love.u_address set state='Alaska' where state='2';
update love.u_address set state='Arizona' where state='3';
update love.u_address set state='Arkansas' where state='4';
update love.u_address set state='California' where state='5';
update love.u_address set state='Colorado' where state='6';
update love.u_address set state='Connecticut' where state='7';
update love.u_address set state='Delaware' where state='8';
update love.u_address set state='Florida' where state='9';
update love.u_address set state='Georgia' where state='10';
update love.u_address set state='Hawaii' where state='11';
update love.u_address set state='Idaho' where state='12';
update love.u_address set state='Illinois' where state='13';
update love.u_address set state='Indiana' where state='14';
update love.u_address set state='Iowa' where state='15';
update love.u_address set state='Kansas' where state='16';
update love.u_address set state='Kentucky' where state='17';
update love.u_address set state='Louisiana' where state='18';
update love.u_address set state='Maine' where state='19';
update love.u_address set state='Maryland' where state='20';
update love.u_address set state='Massachusetts' where state='21';
update love.u_address set state='Michigan' where state='22';
update love.u_address set state='Minnesota' where state='23';
update love.u_address set state='Mississippi' where state='24';
update love.u_address set state='Missouri' where state='25';
update love.u_address set state='Montana' where state='26';
update love.u_address set state='Nebraska' where state='27';
update love.u_address set state='Nevada' where state='28';
update love.u_address set state='New Hampshire' where state='29';
update love.u_address set state='New Jersey' where state='30';
update love.u_address set state='New Mexico' where state='31';
update love.u_address set state='New York' where state='32';
update love.u_address set state='North Carolina' where state='33';
update love.u_address set state='North Dakota' where state='34';
update love.u_address set state='Ohio' where state='35';
update love.u_address set state='Oklahoma' where state='36';
update love.u_address set state='Oregon' where state='37';
update love.u_address set state='Pennsylvania' where state='38';
update love.u_address set state='Rhode Island' where state='39';
update love.u_address set state='South Carolina' where state='40';
update love.u_address set state='South Dakota' where state='41';
update love.u_address set state='Tennessee' where state='42';
update love.u_address set state='Texas' where state='43';
update love.u_address set state='Utah' where state='44';
update love.u_address set state='Vermont' where state='45';
update love.u_address set state='Virginia' where state='46';
update love.u_address set state='Washington' where state='47';
update love.u_address set state='West Virginia' where state='48';
update love.u_address set state='Wisconsin' where state='49';
update love.u_address set state='Wyoming' where state='50';
update love.u_address set state='Puerto Rico' where state='51';
update love.u_address set state='unknown' where state='100';


alter table love.inf_user_address alter column state type varchar(32) using state::varchar(32);

update love.inf_user_address set state='Alabama' where state='1';
update love.inf_user_address set state='Alaska' where state='2';
update love.inf_user_address set state='Arizona' where state='3';
update love.inf_user_address set state='Arkansas' where state='4';
update love.inf_user_address set state='California' where state='5';
update love.inf_user_address set state='Colorado' where state='6';
update love.inf_user_address set state='Connecticut' where state='7';
update love.inf_user_address set state='Delaware' where state='8';
update love.inf_user_address set state='Florida' where state='9';
update love.inf_user_address set state='Georgia' where state='10';
update love.inf_user_address set state='Hawaii' where state='11';
update love.inf_user_address set state='Idaho' where state='12';
update love.inf_user_address set state='Illinois' where state='13';
update love.inf_user_address set state='Indiana' where state='14';
update love.inf_user_address set state='Iowa' where state='15';
update love.inf_user_address set state='Kansas' where state='16';
update love.inf_user_address set state='Kentucky' where state='17';
update love.inf_user_address set state='Louisiana' where state='18';
update love.inf_user_address set state='Maine' where state='19';
update love.inf_user_address set state='Maryland' where state='20';
update love.inf_user_address set state='Massachusetts' where state='21';
update love.inf_user_address set state='Michigan' where state='22';
update love.inf_user_address set state='Minnesota' where state='23';
update love.inf_user_address set state='Mississippi' where state='24';
update love.inf_user_address set state='Missouri' where state='25';
update love.inf_user_address set state='Montana' where state='26';
update love.inf_user_address set state='Nebraska' where state='27';
update love.inf_user_address set state='Nevada' where state='28';
update love.inf_user_address set state='New Hampshire' where state='29';
update love.inf_user_address set state='New Jersey' where state='30';
update love.inf_user_address set state='New Mexico' where state='31';
update love.inf_user_address set state='New York' where state='32';
update love.inf_user_address set state='North Carolina' where state='33';
update love.inf_user_address set state='North Dakota' where state='34';
update love.inf_user_address set state='Ohio' where state='35';
update love.inf_user_address set state='Oklahoma' where state='36';
update love.inf_user_address set state='Oregon' where state='37';
update love.inf_user_address set state='Pennsylvania' where state='38';
update love.inf_user_address set state='Rhode Island' where state='39';
update love.inf_user_address set state='South Carolina' where state='40';
update love.inf_user_address set state='South Dakota' where state='41';
update love.inf_user_address set state='Tennessee' where state='42';
update love.inf_user_address set state='Texas' where state='43';
update love.inf_user_address set state='Utah' where state='44';
update love.inf_user_address set state='Vermont' where state='45';
update love.inf_user_address set state='Virginia' where state='46';
update love.inf_user_address set state='Washington' where state='47';
update love.inf_user_address set state='West Virginia' where state='48';
update love.inf_user_address set state='Wisconsin' where state='49';
update love.inf_user_address set state='Wyoming' where state='50';
update love.inf_user_address set state='Puerto Rico' where state='51';
update love.inf_user_address set state='unknown' where state='100';

update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Alabama"') where consignee_address::json ->> 'state' = '1';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Alaska"') where consignee_address::json ->> 'state' = '2';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Arizona"') where consignee_address::json ->> 'state' = '3';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Arkansas"') where consignee_address::json ->> 'state' = '4';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"California"') where consignee_address::json ->> 'state' = '5';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Colorado"') where consignee_address::json ->> 'state' = '6';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Connecticut"') where consignee_address::json ->> 'state' = '7';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Delaware"') where consignee_address::json ->> 'state' = '8';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Florida"') where consignee_address::json ->> 'state' = '9';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Georgia"') where consignee_address::json ->> 'state' = '10';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Hawaii"') where consignee_address::json ->> 'state' = '11';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Idaho"') where consignee_address::json ->> 'state' = '12';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Illinois"') where consignee_address::json ->> 'state' = '13';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Indiana"') where consignee_address::json ->> 'state' = '14';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Iowa"') where consignee_address::json ->> 'state' = '15';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Kansas"') where consignee_address::json ->> 'state' = '16';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Kentucky"') where consignee_address::json ->> 'state' = '17';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Louisiana"') where consignee_address::json ->> 'state' = '18';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Maine"') where consignee_address::json ->> 'state' = '19';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Maryland"') where consignee_address::json ->> 'state' = '20';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Massachusetts"') where consignee_address::json ->> 'state' = '21';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Michigan"') where consignee_address::json ->> 'state' = '22';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Minnesota"') where consignee_address::json ->> 'state' = '23';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Mississippi"') where consignee_address::json ->> 'state' = '24';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Missouri"') where consignee_address::json ->> 'state' = '25';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Montana"') where consignee_address::json ->> 'state' = '26';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Nebraska"') where consignee_address::json ->> 'state' = '27';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Nevada"') where consignee_address::json ->> 'state' = '28';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"New Hampshire"') where consignee_address::json ->> 'state' = '29';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"New Jersey"') where consignee_address::json ->> 'state' = '30';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"New Mexico"') where consignee_address::json ->> 'state' = '31';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"New York"') where consignee_address::json ->> 'state' = '32';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"North Carolina"') where consignee_address::json ->> 'state' = '33';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"North Dakota"') where consignee_address::json ->> 'state' = '34';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Ohio"') where consignee_address::json ->> 'state' = '35';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Oklahoma"') where consignee_address::json ->> 'state' = '36';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Oregon"') where consignee_address::json ->> 'state' = '37';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Pennsylvania"') where consignee_address::json ->> 'state' = '38';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Rhode Island"') where consignee_address::json ->> 'state' = '39';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"South Carolina"') where consignee_address::json ->> 'state' = '40';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"South Dakota"') where consignee_address::json ->> 'state' = '41';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Tennessee"') where consignee_address::json ->> 'state' = '42';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Texas"') where consignee_address::json ->> 'state' = '43';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Utah"') where consignee_address::json ->> 'state' = '44';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Vermont"') where consignee_address::json ->> 'state' = '45';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Virginia"') where consignee_address::json ->> 'state' = '46';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Washington"') where consignee_address::json ->> 'state' = '47';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"West Virginia"') where consignee_address::json ->> 'state' = '48';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Wisconsin"') where consignee_address::json ->> 'state' = '49';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Wyoming"') where consignee_address::json ->> 'state' = '50';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"Puerto Rico"') where consignee_address::json ->> 'state' = '51';
update love.o_order set consignee_address = jsonb_set(consignee_address::jsonb, '{state}', '"unknown"') where consignee_address::json ->> 'state' = '100';